apiVersion: v1
kind: Secret
metadata:
  name: {{ include "co-tracker.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "co-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $users := .Values.app.auth.users | default (dict "admin" "admin") }}
  USERS_JSON: {{ $users | toJson | quote }}
