apiVersion: v1
kind: Service
metadata:
  name: {{ include "co-tracker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "co-tracker.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "co-tracker.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
